In [0]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


In [0]:
steps=[("standard scaler",StandardScaler()),("Classifier",LogisticRegression())]

In [0]:
steps

[('standard scaler', StandardScaler()), ('Classifier', LogisticRegression())]

In [0]:
pipe=Pipeline(steps)

In [0]:
from sklearn import set_config
set_config(display="diagram")
pipe

Pipeline(steps=[('standard scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [0]:
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000)

In [0]:
x.shape

(1000, 20)

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)


In [0]:
x_train

array([[ 1.43874172,  0.44292994,  1.33709079, ..., -0.24472094,
        -0.89871565,  0.7992571 ],
       [-1.12613434, -1.67179565, -2.61921167, ...,  2.6810653 ,
         0.29364859,  0.30432627],
       [ 0.22392271, -0.86772314,  1.20506836, ...,  0.06410568,
         0.02866824,  0.50614677],
       ...,
       [ 1.46920078,  1.95377729,  1.67624291, ..., -0.21875408,
         0.3854187 ,  0.66022746],
       [-0.60847598, -1.477779  , -1.61674765, ..., -0.1552329 ,
        -1.66432716, -0.55335602],
       [ 1.24175577, -0.61750941,  0.7527821 , ..., -2.47104321,
         0.90846374, -1.63774592]])

In [0]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('standard scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [0]:
Pipeline(steps=[('standard scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])
y_predict=pipe.predict(x_test)
y_predict

array([1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,

In [0]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [0]:
steps=[('Scaling',StandardScaler()),
       ('PCA',PCA()),
       ('classifier',SVC())]
pipe2=Pipeline(steps)
pipe2.fit(x_train,y_train)
Pipeline(steps=[('Scaling', StandardScaler()),
                ('PCA', PCA()),
                ('classifier', SVC())])
pipe2.predict(x_train)

array([1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,

In [0]:
from sklearn.impute import SimpleImputer
import numpy as np

In [0]:
numeric_processor = Pipeline(steps=['imputation',SimpleImputer(missing_values=np.nan,strategy='mean'),('scaler',StandardScaler())])
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(

steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
 ("onehot",OneHotEncoder(handle_unknown="ignore"))]
)
categorical_processor

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [0]:
from sklearn.compose import ColumnTransformer
preprocessor=ColumnTransformer(
 [("categorical",categorical_processor,["gender","City"]),
 ("numerical",numeric_processor,["age","height"])]
)
preprocessor
ColumnTransformer(transformers=[('categorical',

Pipeline(steps=[('imputation_consatnt',

SimpleImputer(fill_value='missing',

strategy='constant')),
 ('onehot',

OneHotEncoder(handle_unknown='ignore'))]),
 ['gender', 'City']),
 ('numerical',
 Pipeline(steps=[('imputation_mean',
 SimpleImputer()),
 ('scaler',
StandardScaler())]),
 ['age', 'height'])])


ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [0]:
from sklearn.pipeline import make_pipeline
pipe=make_pipeline(preprocessor,LogisticRegression())
pipe
Pipeline(steps=[('columntransformer',
 ColumnTransformer(transformers=[('categorical',

Pipeline(steps=[('imputation_consatnt',

SimpleImputer(fill_value='missing',

strategy='constant')),

('onehot',

OneHotEncoder(handle_unknown='ignore'))]),
 ['gender', 'City']),
 ('numerical',

Pipeline(steps=[('imputation_mean',

SimpleImputer()),

('scaler',
StandardScaler())]),
 ['age',
'height'])])),
 ('logisticregression', LogisticRegression())])

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])